### ISSUE TITLE
Random pictures problem.

### ISSUE THREAD

**Issue by pimagical** [philipbeel/Flickrush#2]
No random pictures when limit = 1

**Comment by philipbeel** [comment]
Try -1

**Comment by pimagical** [comment]
With -1 no images are being displayed.

The limit is not only the browser output but it is also the selected input.
That's why the random function won't work if a limit of one picture is selected.

Your nice code is almost perfect! ;-)

**Comment by philipbeel** [comment]
Let me take a look into this.

**Comment by pbeel** [comment]
Updated repo. Flickrush v1.4 

Stopped randomising ordering when only 1 item is passed in the limit.

**Comment by philipbeel** [comment]
Issue with randomising and limiting to 1 photo has been resolved in master.

**Comment by pimagical** [comment]
With limit 1 the same foto is shown when page is refreshed.

**Comment by philipbeel** [comment]
Randomising works by randomising the order of the photos are displayed;

- For 10 photos, position 1 could be photo source 1-10 and so on.
- For 1 photo, position 1 could be photo source 1-1 - the same
 
I think there is a little confusion on your part to what this functionality should be. That said I will look to create a branch that implements your feature requirements. I do not however believe this should be merged into master.

**Comment by philipbeel** [comment]
Please checkout this branch for your 'bespoke' requirements: 
https://github.com/philipbeel/Flickrush/tree/feature-limit

**Comment by pimagical** [comment]
Sorry i was not clear enough. I want to display one image at a time and refresh the page/image every 10 seconds with a random photo from the album without a limit.
