### ISSUE TITLE
Question about item.media.m

### ISSUE THREAD

**Issue by pimagical** [philipbeel/Flickrush#3]
Question about the item.media.m (m stands for medium size image) in jquery.flickrush.js

I tested with item.media.b (b stands for full size image) and other image size suffixes but only m seems to works. More information about Size Suffixes at https://www.flickr.com/services/api/misc.urls.html

Do you know what im doing wrong or what need to be changed?

**Comment by philipbeel** [comment]
I was not aware of this. I have added this functionality here:
https://github.com/philipbeel/Flickrush/tree/feature-limit

README.md has also been updated to reflect how you ca use this.
